### ISSUE TITLE
Merge design discussion

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pfs#16]
Pfs currently has branching which is very similar to git's but doesn't have a concept of merging. It's not immediately obvious what merge maps to in pfs. One obvious issue is that big data merge conflicts sound pretty miserable. The only idea I have for how to solve that is to let users submit a container as a merging function.

**Comment by jdoliner** [comment]
One possible way of addressing this issue is using overlayfs as described in #28 .

**Comment by derekchiang** [comment]
Merge has been added in #641.
