### ISSUE TITLE
Job images can only be pulled from the Docker Registry

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pfs#24]

**Comment by versae** [comment]
One question I have, is it working with privately-run Docker registries. If so, why not having Pachyderm to run their own registry at least in one node? I see a `registry.service` in the `1Node`, but not sure how to use it.

Also, that raises more questions, like should the registry work in high availability mode in the cluster? If not, maybe a Paxos-based approach might work. Or maybe by pulling the docker files from git could remove the need for the docker registry?

Sorry if what I'am saying is nonsense, the project just looks really amazing and I got excited :)

**Comment by JoeyZwicker** [comment]
@versae We're thrilled that it excites you so much. Us too!  :)

We're about to push out pfs v0.4 in the next few hours and I think you'll really like it. It includes support for privately-run docker registries inside the cluster and it's in high-availability mode by default. 

We also will be rolling out a pretty in-depth integration with git that includes pulling docker files and bunch more cool stuff.

**Comment by versae** [comment]
Just can't express me feelings with words
![](http://i.imgur.com/dhMeAzK.gif)

**Comment by jdoliner** [comment]
This has been fixed for a while. You can pull containers from any registry you'd like.

We had to temporarily unsupport the registry in the cluster due to some annoyances with certificates.
We'll be trying to get that reenabled soon!
