### ISSUE TITLE
Streamline Pachyderm installation

### ISSUE THREAD

**Issue by versae** [pachyderm/pfs#39]
I know that is dead simple already, 3 commands is pretty cool. I was just thinking if something like the next would be useful:
```
$ wget -qO- install.pachyderm.io | sh
```
And even having different shell scripts depending on the platform.
```
$ wget -qO- install.pachyderm.io/mesos | sh
$ wget -qO- install.pachyderm.io/coreos | sh
```
Although I understand that some people may prefer to know what exactly are they doing.

**Comment by JoeyZwicker** [comment]
one-line installation is available and there C2D on AWS.
