### ISSUE TITLE
Readme incorrectly instructs users to set S3 bucket in registry

### ISSUE THREAD

**Issue by damnMeddlingKid** [pachyderm/pfs#43]
The line 

"etcdctl set /pfs/registry/IMAGE_BUCKET <IMAGE_BUCKET>"

should be 

"etcdctl set /pfs/creds/IMAGE_BUCKET <IMAGE_BUCKET>"

**Comment by jdoliner** [comment]
And I would have gotten away with it too if it wasn't for those damned meddling kids.

I think @JoeyZwicker just fixed this one. Thanks for the heads up @damnMeddlingKid we appreciate it.

**Comment by damnMeddlingKid** [comment]
hehe , you also need to fix this on docker hub https://registry.hub.docker.com/u/pachyderm/pfs/
