### ISSUE TITLE
Cannot support Docker 1.6.0

### ISSUE THREAD

**Issue by waitingkuo** [pachyderm/pfs#52]
https://github.com/pachyderm/pfs/blob/master/scripts/launch#L31-L35

According to the docker version check, pfs only supports docker1.5.0 now. Can I install pfs on top of Docker 1.6.0 by manually removing that docker version check?

**Comment by brendanashworth** [comment]
I installed it on 1.6.0 (Ubuntu 14.04) by removing the check. You can apply the patch I just submitted if you'd like, as 1.6.0 is supposed to be supported (README states >= 1.5.0).

**Comment by waitingkuo** [comment]
thanks~

**Comment by jdoliner** [comment]
The fix mentioned by @brendanashworth has been merged in to master. Closing.
