### ISSUE TITLE
Noob question: does this work on a Mac?

### ISSUE THREAD

**Issue by alexed1** [pachyderm/pfs#56]
Eager to try pachyderm out, this is what I'm running into:

on a mac, using boot2docker, in a working docker environment:

running "curl www.pachyderm.io/launch | sh"
results in "Please install btrfs-tools. (apt-get install btrfs-tools)"

however, typing "sudo apt-get install btrfs-tools" produces:

Reading Package Lists... Done
Building Dependency Tree... Done
E: Couldn't find package btrfs-tools

I experimented with runing a vanilla ubuntu container, and from there I was able to install btrfs-tools. But then I have to add a docker installation to the container, which leads to weird port errors that are probably due to docker in docker strangeness, and which are beyond my ability to debug.

Apologies for putting this usage question to the git issues....I don't know a better place short of emailing the pachyderm project leaders.

Anyways, very cool project.

**Comment by jdoliner** [comment]
Hi @alexed1 first off git issues is 100% the right stuff for things like this.

Unfortunately we don't have great support for running pfs on OSX. I'm going to look in to what it would take to get this working nicely with boot2docker. The only difficult part is getting btrfs up and working and it looks like that should be possible according to [this](https://github.com/boot2docker/boot2docker/blob/master/doc/WORKAROUNDS.md#btrfs-ie-mkfs-inside-a-privileged-container).

For the time being I think your best bet is going to be running a CoreOS VM using Vagrant. I realize that's not the best install experience, we'll try to have a more native OSX experience soon.

**Comment by alexed1** [comment]
ok, will try that.
