### ISSUE TITLE
would love a getting started tutorial

### ISSUE THREAD

**Issue by peter-edge** [pachyderm/pfs#81]
I started dev'ving on a mac a few years ago - not completely sure why, but iMessage is fun haha. But ya, pfs overall needs a good "getting started" that's universal, and with assumptions, ie

- this is the operating system/things to install that we recommend for developing
- this is how you start a local cluster and what you need installed
- here's some vagrant files/docker files/etc we'll keep updated

would help a ton for a lot of people i bet

**Comment by DazWilkin** [comment]
+1

**Comment by JoeyZwicker** [comment]
+1000 We're working on this. This month's release cycle is going to include a ton of documentation that should cover these types of issues. Making that early hacking experience better is huge.
