### ISSUE TITLE
replace all 'sudo docker' calls with 'docker'?

### ISSUE THREAD

**Issue by peter-edge** [pachyderm/pfs#82]
Wanted to get the motivation here, maybe there's more to it - I know that only using `sudo` within a script on a command that requires it makes for better permission granularity, but...eh :) having `sudo` preface all docker commands is a pain for development for the large of those who are either have a docker group, or do something else  with mac (my docker command is aliased to hell, for example).

**Comment by jdoliner** [comment]
Definitely in favor of this.

Motivation was mostly, "this seems like the easiest way to get this script to work right now." So rethinking is welcome here.

**Comment by peter-edge** [comment]
Done
