### ISSUE TITLE
Add a /log route.

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pfs#88]
Currently the only way to get logs out of a server is to go to the local filesystem and find them. It'd be nice if we could just get them via http. We also might want to expose them in other ways but this is a good start.

**Comment by phacops** [comment]
Is anyone working on this yet? If not, I'll start working on it.

**Comment by jdoliner** [comment]
Dukes, I just merged this in to next. I'm going to label some more noob friendly issues.
